nefarian_plugins:
  resource:   .
  type:       nefarian_plugins

nefarian_api:
  resource:   .
  type:       nefarian_api

#nefarian_cms_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: NefarianCmsBundle:Default:index }


