parameters:
    nefarian_cms.config_manager.class: Nefarian\CmsBundle\Configuration\ConfigManager

services:
    nefarian_cms.config_manager:
        class: %nefarian_cms.config_manager.class%
        arguments: [@doctrine.orm.default_entity_manager]
