parameters:
  nefarian_core.config_manager.class:        Nefarian\CmsBundle\Configuration\ConfigManager
  nefarian_core.menu_manager.class:          Nefarian\CmsBundle\Menu\MenuManager
  nefarian_core.content_manager.class:       Nefarian\CmsBundle\Content\ContentManager
  nefarian_core.content_field_manager.class: Nefarian\CmsBundle\Content\Field\ContentFieldManager

  # Routing
  nefarian_core.routing.plugin_loader.class: Nefarian\CmsBundle\Router\PluginLoader
  nefarian_core.routing.api_loader.class:    Nefarian\CmsBundle\Router\ApiLoader

  # Theming
  nefarian_core.theme_manager.class:  Nefarian\CmsBundle\Theme\ThemeManager
  nefarian_core.theme_loader.class:   Nefarian\CmsBundle\Twig\Loader\ThemeLoader
  nefarian_core.plugin_loader.class:  Nefarian\CmsBundle\Twig\Loader\PluginLoader

  # override the asset factory
  assetic.asset_factory.class: Nefarian\CmsBundle\Assetic\Factory\NefarianAssetFactory

  # Doctrine
  nefarian_core.content_fields.doctrine.mapping.listener.class: Nefarian\CmsBundle\Doctrine\FieldMappingListener

services:

  #
  # Managers
  nefarian_core.config_manager:
    class: %nefarian_core.config_manager.class%
    arguments: [@doctrine.orm.default_entity_manager]

  nefarian_core.menu_manager:
    class: %nefarian_core.menu_manager.class%

  nefarian_core.content_manager:
    class: %nefarian_core.content_manager.class%
    arguments:
      - @nefarian_core.content_field_manager

  nefarian_core.content_field_manager:
    class: %nefarian_core.content_field_manager.class%

  #
  # Plugin - Routing
  nefarian_core.routing.plugin_loader:
    class: %nefarian_core.routing.plugin_loader.class%
    tags:
      - { name: routing.loader }
  nefarian_core.routing.api_loader:
    class: %nefarian_core.routing.api_loader.class%
    tags:
      - { name: routing.loader }

  #
  # Plugin - Twig Loader
  twig.loader.plugin_loader:
    class: %nefarian_core.plugin_loader.class%
    arguments:
      - @templating.locator
      - @templating.name_parser
    tags:
      - { name: twig.loader }


  #
  # Theming
  nefarian_core.theme_manager:
    class: %nefarian_core.theme_manager.class%

  twig.loader.theme_loader:
    class: %nefarian_core.theme_loader.class%
    arguments:
      - @nefarian_core.theme_manager
      - @templating.locator.theme_filesystem_locator
      - @templating.name_parser
    tags:
      - { name: twig.loader }

  #
  # Template loader!
  templating.locator.theme_locator:
    class: Nefarian\CmsBundle\Templating\Locator\ThemeLocator
    arguments:
      - @nefarian_core.theme_manager

  templating.locator.theme_filesystem_locator:
    class: %templating.locator.class%
    arguments:
      - @templating.locator.theme_locator
      - %kernel.cache_dir%

  templating.loader.theme_loader:
    class: %templating.loader.filesystem.class%
    arguments:
      - @templating.locator.theme_locator

  #
  # Doctrine - Mapping listener to modify relationships
  nefarian_core.content_fields.doctrine.mapping.listener:
    class: %nefarian_core.content_fields.doctrine.mapping.listener.class%
    arguments:
      - @nefarian_core.content_field_manager
      - %doctrine.orm.proxy_dir%
      - Nefarian\CmsBundle\Plugin\ContentManagement\Entity\Field
      - %doctrine.orm.auto_generate_proxy_classes%
    tags:
      - { name: doctrine.event_listener, event: loadClassMetadata }
      - { name: doctrine.event_listener, event: postUpdate }
      - { name: doctrine.event_listener, event: preUpdate }
