nefarian_plugins_list:
    path:     /
    defaults: { _controller: NefarianCmsBundle:Plugin/Plugin:list }

nefarian_plugins_enable:
    path:     /
    type:     rest
    defaults: { _controller: NefarianCmsBundle:Plugin/Plugin:enablePlugin }

nefarian_plugins:
  resource:   .
  type:       nefarian_plugins